Enh#11
cheminfIBB/cheminfibb.github.io pull request #30
Opened 2018-09-26 13:10 UTC by henryk69

# Enhancements

Updated whole page - should be fully featured now. Please check.

Missing: 
1. missing information should be filled (shown as FIXME) - mainly emails and phone no. No separate issue needed.
2. missing photos - see issue #28 
3. Links to homepages should be fixed - they should link to real empty pages for each person to fill #29

2018-09-26 14:16 UTC, dizak requested changes
There should be no style attributes in the HTML here. This is reverting the clean-up I did, you must have overwritten them.

2018-09-27 11:15 UTC, dizak requested changes
You should remove the attributes NOT the whole tags

2018-09-27 11:15 UTC, dizak commented on people.md
> -  <ul style="list-style-type:none;">
You should NOT remove the whole opening tag, just ```style``` attribute:
```html
<ul>
```

2018-09-27 11:15 UTC, dizak commented on people.md
>      <li><p style="margin-bottom: 0px"><a href="http://webjeda.com/online-cv/">Agnieszka Gromadka, MSc</a></p></li>
You should remove ```style``` attribute from the paragraph, like so:

```html
<li><p><a href="http://webjeda.com/online-cv/">Agnieszka Gromadka, MSc</a></p></li>
```
It applies to all ```<li>``` tags below

2018-09-27 11:15 UTC, dizak commented on people.md
> -  <ul style="list-style-type:none;">
You should NOT remove the whole opening tag, just ```style``` attribute:
```html
<ul>
```

2018-09-27 11:15 UTC, dizak commented on people.md
> -  <ul style="list-style-type:none;">
You should NOT remove the whole opening tag, just ```style``` attribute:
```html
<ul>
```

2018-09-27 11:15 UTC, dizak commented on people.md
> -  <ul style="list-style-type:none;">
You should NOT remove the whole opening tag, just ```style``` attribute:
```html
<ul>
```

2018-09-27 11:15 UTC, dizak commented on people.md
> -  <ul style="list-style-type:none;">
You should NOT remove the whole opening tag, just ```style``` attribute:
```html
<ul>
```

2018-09-27 11:15 UTC, dizak commented on people.md
> -  <ul style="list-style-type:none;">
You should NOT remove the whole opening tag, just ```style``` attribute:
```html
<ul>
```

2018-09-27 11:15 UTC, dizak commented on people.md
> -  <ul style="list-style-type:none;">
You should NOT remove the whole opening tag, just ```style``` attribute:
```html
<ul>
```

2018-09-27 11:15 UTC, dizak commented on people.md
> -  <ul style="list-style-type:none;">
You should NOT remove the whole opening tag, just ```style``` attribute:
```html
<ul>
```

2018-09-27 11:15 UTC, dizak commented on people.md
> -  <ul style="list-style-type:none;">
You should NOT remove the whole opening tag, just ```style``` attribute:
```html
<ul>
```

2018-09-27 12:28 UTC, dizak approved these changes
OK!

2018-09-28 13:11 UTC, merged

2018-09-28 13:11 UTC, henryk69 commented
this is so cool - I love merging changes!